image: ghcr.io/home-assistant/{arch}-base-ubuntu
build_from:
  amd64: "registry.access.redhat.com/ubi9/ubi:"
cosign:
  identity: https://github.com/TwoDCube-Home/homeassistant-docker-base/.*
args:
  BASHIO_VERSION: 0.16.2
  TEMPIO_VERSION: 2024.11.2
  S6_OVERLAY_VERSION: 3.1.6.2
labels:
  io.hass.base.name: ubi9
  org.opencontainers.image.source: https://github.com/TwoDCube-Home/homeassistant-docker-base
