name: Build base images

on:
  release:
    types: ["published"]

env:
  BUILD_TYPE: base
  UBI9_LATEST: "9.5"

jobs:
  init:
    name: Initialize build
    runs-on: ubuntu-22.04
    outputs:
      release: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Get version
        id: version
        uses: home-assistant/actions/helpers/version@master
        with:
          type: ${{ env.BUILD_TYPE }}

  build_ubi9:
    name: Build ubi9 base image
    needs: init
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4.2.2

      - name: Login to GitHub Container Registry
        if: github.event_name == 'release'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build base image
        uses: home-assistant/builder@2025.03.0
        with:
          args: |
            $BUILD_ARGS \
            --target /data/ubi9 \
            --cosign \
            --release ${{ needs.init.outputs.release }} \
            --base ${{ matrix.version }}
